version: '3.6'

services:
  db:
    image:postgresql
    environment:
      POSTGRES_URL=
      POSTGRES_PASSWORD='root'
    volumes:
      - './var/lib/postgresql/data'
  gochain:
    image: t????
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IP:
        PORT: 8000

