version: '3.6'

networks:
  n1:

services:
  db:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=root'
    volumes:
      - './db:/var/lib/postgresql/data'
    networks:
      - 'n1'
    restart: always
    user: 1000:1000

  gochain:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './blockchain.html:/blockchain.html'
    environment:
      - 'IP=0.0.0.0'
      - 'PORT=8000'
      - 'POSTGRES_URL=db'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '8000:8000'
    depends_on: 
      - 'db'
    networks:
      - 'n1'
    links:
      - 'db'
